src/gz base https://ws1608.ggff.net/arm_cortex-a5_neon-vfpv4/base
src/gz kmod https://ws1608.ggff.net/arm_cortex-a5_neon-vfpv4/kmod
src/gz luci https://ws1608.ggff.net/arm_cortex-a5_neon-vfpv4/luci
src/gz packages https://ws1608.ggff.net/arm_cortex-a5_neon-vfpv4/packages