src/gz kwrt_core https://dl.openwrt.ai/23.05/targets/amlogic/meson8b/5.15.167
src/gz kwrt_base https://dl.openwrt.ai/23.05/packages/arm_cortex-a5_vfpv4/base
src/gz kwrt_packages https://dl.openwrt.ai/23.05/packages/arm_cortex-a5_vfpv4/packages
src/gz kwrt_luci https://dl.openwrt.ai/23.05/packages/arm_cortex-a5_vfpv4/luci
src/gz kwrt_routing https://dl.openwrt.ai/23.05/packages/arm_cortex-a5_vfpv4/routing
src/gz kwrt_kiddin9 https://dl.openwrt.ai/23.05/packages/arm_cortex-a5_vfpv4/kiddin9
